-- AlterTable
ALTER TABLE "Order" ADD COLUMN "subtotalAmount" DOUBLE PRECISION DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN "deliveryAmount" DOUBLE PRECISION DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN "expressAmount" DOUBLE PRECISION DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN "gstAmount" DOUBLE PRECISION DEFAULT 0;